version: '3'
services:
    jekyll:
        image: jekyll/jekyll:latest
        container_name: takacsmark-dot-com
        # working on one post - use incremental mode
        # command: jekyll serve --host 0.0.0.0 --drafts --config _config.yml,_config_dev.yml --watch --incremental

        # add new post - no incremental mode, Jekyll will regenerate dependencies on save
        command: jekyll serve --host 0.0.0.0 --drafts --config _config.yml,_config_dev.yml

        # work on design - no incremental mode, no drafts, looks like production
        # command:jekyll serve --host 0.0.0.0 --config _config.yml,_config_dev.yml --watch

        volumes:
            - $PWD:/srv/jekyll
            - $PWD/vendor/bundle:/usr/local/bundle

        ports:
            - 4000:4000
            - 35729:35729
